# Generated by Django 5.1 on 2024-08-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('pg', models.IntegerField(verbose_name=2)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
