# Generated by Django 5.1 on 2024-08-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_streamdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdetail',
            name='pg',
            field=models.IntegerField(),
        ),
    ]
