# Generated by Django 5.1 on 2024-08-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_alter_streamdetail_pg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamDetail',
        ),
    ]
