# Generated by Django 5.1 on 2024-08-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0009_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='reviewer_user',
        ),
    ]
